plugins:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - spec/
      - app/assets/javascripts/
  method-lines:
    enabled: true
    exclude_paths:
      - app/assets/javascripts/
