inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - config/initializers/devise.rb
    - 'node_modules/**/*'
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Lint/UselessAssignment:
  Exclude:
    - 'config/initializers/sidekiq.rb'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/sidekiq.rb'