language: ruby

rvm:
  - 2.5.0

env:
  global:
    - CC_TEST_REPORTER_ID=ENV["CODECLIMATE_TAG"]

before_script:
  - gem update --system
  - gem install bundler
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec bin/rails db:create
  - bundle exec bin/rails db:migrate
  - bundle exec rspec
  - bundle exec rubocop

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "qj91epnXyoMF1OwgUZ4xvY6i8nhYFfRgJIE99jPZx7wedwbIcriIh36YFPPUqOJA1Z0fUE+qZ7WKTOJWfmufrJ6O704BGtOVZXFVz6eCockad78HkezFS91uQUtgKZ0gWurXlraG83jNKjQ3Y8HDM7rh4FLWsTXtRkJTSFTh91tvX2psLMnHxjtIN0xQEYYm76Cv0egcbJidU7EgAJuYdvlpt+3rVWjNGpK4HmiWlBXS+8SZ8A+QQdrmUvJxxPgZ8p7ZuR2JiyeLKlVDNGBQRvhdm5L/Q+RutU9EByC+CybdjAf6rK1fA+hheVm+FYXHjZxHTnRf6/X5Suc73BsA76+VH61d0kpvnyKq0hWhscqC5NilWqf+fvhTLhtQ6YIOwuxeOCN/1U2TRRagiEDodqUtgXtCcMoXN++kJ/wMMuvgyMqE7TmNvHg1EHUcC7F45YQxl/xHDasA1BCQkWJnYrxquS6gCCFRXebzAeQYtpH3A+c29lCPkV5uRsA1K/jJ8XXgmu6Wg3LU3yWKW3uT8tLjltsxIH1/1cbXDpRsRMSpWXDCUf1L0cygdyBu+IWhynl8KD0t9W6+IfTyTiTu78TIJZUeZvXLTLxlWO1zR2+zdjneeqZf2v6zzm+xfedZo8tJN4OvKVHFseWYOxronY517DiBFJHlxhKymNsAdhc="
  secret_access_key:
    secure: "qW6MgeU2GQsJwtxhFGdqVOr/xeModuchuHZohftYlgIk/ijlOXOKKSOKxRNJW0DDkYp4X++HVaHp3D/4aU2EinWt7tDcVbb/nrHlNiqXv3BhlXAqFa7c3kiXx7cz9Z+6tf7rVXYlsNty/oRIpG18rRGXyNXJpFs6sE/Fi2KIZOK6TIaMqU9Lw4qtuCZ/vP1TwpKXLY/ENYfEuzwss2nw70nH/OWqAkclZlx63H1uuo4UufH8Bd5RAKk48Ma2BlmsdC08Rv7iny2kfiPpS25LrcLiu1yjlFY8njA8sExgINrhLMxeG4yAp9OVxRWfn8cNdbTDxfAiZqtVglWIjk8noQj+i9vFnFq72zbRY3f5W5Vl9nL6ihXQSDjtLD13348noY9i9Tt9zWwOItk6iyJYN6peVWAhjMpftK+LrNhBDOhVbWNUTqLLGM7my3CcuHADyW8OQMVmdyaX8YzG3tp8O+jqgUJUJREfmXIeo3aMtx9E1eaXr0iy7awnxCs+tRQUzDuGvNEwriGE+MrbUmz7m5B57OvhWRUePJYkUfcQxxuA7Qfi0U3/EZBvzpXgZXRCHAtCuc87CjzeOdBnWiYKnw3+26M29MyOWHI+RXm5B7qiOH9sLXFib/MlRnjRUJELyqMBMfQmOVtVT2Y/89CRSU7rfUMXUtEuVH1nbDX68Sk="
  region: eu-west-2
  app: acebook-ciCADA
  env: acebook-ciCADA-dev
  bucket_name: 'elasticbeanstalk-eu-west-2-423668963318'
  on:
    repo: Kharouk/acebook-ciCADA
    branch: master
