language: ruby

rvm:
  - 2.5.0

env:
  global:
    - CC_TEST_REPORTER_ID=ENV["CODECLIMATE_TAG"]

before_script:
  - gem update --system
  - gem install bundler
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec bin/rails db:create
  - bundle exec bin/rails db:migrate
  - bundle exec rspec
  - bundle exec rubocop

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: elasticbeanstalk
  access_key_id: ENV["EB_KEY_ID"]
  secret_access_key:
    secure: ENV["EB_SA_KEY"]
  region: eu-west-2
  app: acebook-ciCADA
  env: acebook-ciCADA-dev
  bucket_name: 'elasticbeanstalk-eu-west-2-423668963318'
  on:
    repo: Kharouk/acebook-ciCADA
    branch: master
